services:
  app:
    build: .
    restart: unless-stopped
  reverse-proxy:
    image: nginx:1.27.3
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/data/www
    environment:
      - NGINX_HOST=example.com
      - NGINX_PORT=80
    links:
      - app
   certbot:
     image: certbot/certbot:1.7.0
     restart: unless-stopped
     volumes:
       - ./certbot/www:/var/www/certbot/:rw
       - ./certbot/conf:/etc/letsencrypt/:rw

