services:
  app:
    build: .
  reverse-proxy:
    image: nginx:1.27.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/data/www
    environment:
      - NGINX_HOST=example.com
      - NGINX_PORT=80
    links:
      - app
