name: build-deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VPS_RSA }} 
        known_hosts: ${{ secrets.VPS_HOST }}
    - name: checkout
      uses: actions/checkout@v1
    - name: Setup node.js environment
      uses: actions/setup-node@v3.4.1
      with: 
        node-version: 16.x
    - run: npm i -g yarn
    - run: yarn
    - run: yarn build
    - run: touch .env
    - run: echo "NEXT_PUBLIC_ANILIST_URL=${{ secrets.ANILIST_URL }}" > .env
    - run: cd ../ && tar -czf next-speed-dial.tar.gz ./next-speed-dial/
    - run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} 'rm -rf ~/next-speed-dial/'
    - run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} 'pm2 stop next-speed-dial'
    - run: cd ../ && scp -r ./next-speed-dial.tar.gz ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:~/next-speed-dial.tar.gz
    - run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} 'tar -xf next-speed-dial.tar.gz'
    - run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} 'rm -f next-speed-dial.tar.gz'
    - run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} 'pm2 start next-speed-dial'
