name: build-deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Setup node.js environment
      uses: actions/setup-node@v3.4.1
      with: 
        node-version: 16.x
    - run: npm i -g yarn
    - run: yarn
    - run: yarn build
    - run: touch .env
    - run: echo "ANILIST_URL=${{ secrets.ANILIST_URL }}" > .env
    # - run: tar -cvzf next-speed-dial.tar.gz .
    - run: scp -r ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:~/next-speed-dial/