name: build-deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node.js environment
      uses: actions/setup-node@v3.4.1
      with: 
        node-version: 16.x
    - name: Yarn
      run: npm i -g yarn
    - name: LS0
      run: cd ../../ && ls -a
    # - name: Install
      # run: yarn i
    # - name: Build
      # run: yarn build
      
        
    
      
